### ISSUE TITLE
Workflow doesn't work

### ISSUE THREAD

**Issue by atanasj** [flegfleg/alfred-pandoc-clipboard-convert#1]
Hi

Trying to convert markdown to RTF. I use the recommended command i.e., ```'panclip markdown-RTF'```, but no joy. This is the error I'm getting from the alfred debugger:

```
[WARNING] Could not fetch resource 'Pandoc-Icon/Pandoc-Icon.png': andocResourceNotFound "Pandoc-Icon/Pandoc-Icon.png"
[2018-01-12 20:19:05][input.keyword] Processing output of 'action.script' with arg 'markdown-RTF'
[2018-01-12 20:19:06][ERROR: action.script] [WARNING] Could not fetch resource 'Pandoc-Icon/Pandoc-Icon.png': PandocResourceNotFound "Pandoc-Icon/Pandoc-Icon.png" 
```

I'm hoping you can help. I am using the following software:

```
MacOS 10.13.2
pandoc 2.0.4
```

Thanks in advance.

**Comment by flegfleg** [comment]
Hi, does pandoc work with its standard usage? 
http://pandoc.org/MANUAL.html#using-pandoc

**Comment by atanasj** [comment]
Hi... Long time coming, but yes, `pandoc` works otherwise as expected.

**Comment by thorstenmerl** [comment]
same here, 
the CLI is working. For example the command `pandoc atest.md -o atest.docx` generates a perfect Word-Doc.
Alfred notifies me that it is processing/converting, but the Clipboard is empty afterwards.

**Comment by flegfleg** [comment]
Hi, sorry for my late answer. 

panclip can not write rich text "files" (rtf, docx, etc) to the clipboard. It uses the shell command `pbcopy` which, as far as i know, does not handle rich text (and its file headers!). 

I have updated the readme to reflect this. 

Flo

**Comment by flegfleg** [comment]
upon further reading, turns out i was wrong: https://unix.stackexchange.com/questions/84951/copy-markdown-input-to-the-clipboard-as-rich-text/84952#84952

You can achive this, but it would require a rewrite of the shell script to conditionally trigger different  copy commands based on the output format. Seems quite straight forward, but I do not have the time to do that, unfortunately. Feel free to open a pull request. 

If you only require the same (e.g. markdown->rich text) conversation, you could just fork the repo and use the code i linked.  

closing this now.
